CREATE TABLE `test3` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `fio` TEXT NOT NULL,
  `gruppa` VARCHAR (10) NOT NULL,
  `date` VARCHAR (20) NOT NULL,
    `shkala_1` VARCHAR (10) NOT NULL,
    `res_1` TEXT,
    `shkala_2` VARCHAR (10) NOT NULL,
    `res_2` TEXT,
    `shkala_3` VARCHAR (10) NOT NULL,
    `res_3` TEXT,
    `shkala_4` VARCHAR (10) NOT NULL,
    `res_4` TEXT,
    `shkala_5` VARCHAR (10) NOT NULL,
    `res_5` TEXT,
    `shkala_6` VARCHAR (10) NOT NULL,
    `res_6` TEXT,
    `shkala_7` VARCHAR (10) NOT NULL,
    `res_7` TEXT,
  PRIMARY KEY (`ID`)
);